language: node_js
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
deploy:
  provider: npm
  email: denis.sablic@gmail.com
  api_key:
    secure: Rv/1E2onkGFTEBxZ/UxGhBp3Vehd8Gmxudq3tDsjiLTsnPCJHOgda1NvmowfjsZw7c8dTootbvbVvJpYtIb3SWlCDzwwgYt8n26sEIcDFnyEyVTrUFqnVS4Vv+k22/IhXWdZPIUltAFPNb51Lt42k45T3DQ/HsKxi4BAqvRkM7VNkKFmPfDxi9uRTz7jyI/+NRfxrh6F4Gxu8hd7Zn9aKONc56ByKfOJA89xOMLdKyWoLIUD5X1IiJVSSRYH0aCZlPIg3AZyx66AEfG6fnnGnLAddIz1zsJEe33scvXN8FVjTSMGLU9Jy3qy2nlJbXJJYcYqcCxpA2x+kyayyLMN8ixPTq+zugfkzajLKPdAMBSNGN649aeZ6FEHkpqekZtS+SWgy5OXjiwZsfCJiDOFh0Jmlog0MmaSC/wSpw4x1gmb6Xs1tK8xYKMJqwzXFHCx9++HuAppM5MQSCEruhGAqCoFM6ZSaNiCO1bM9ro5tj8juQm/pM/4B7qj0j5QnKh3jK9YGwBvsPz7pGcbeyZ06j8NpAA94uSLnkxWeRn2HmA8ySGJdyxy5WXXDCXZcyOMkgA5SSoLZ3d2YtltfQyQvL3EUwOwyvN/3HV5KEFAruhjoFl9RG8JHeUka4cQQQw7agpA3CrF+j3WC00v3CcNdEeNaGuo2LnY7sbY4hKL294=
  on:
    tags: true
